/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AiJobsRouteImport } from './routes/ai-jobs'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as CandidatesRouteImport } from './routes/candidates'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as EthicsRouteImport } from './routes/ethics'
import { Route as InterviewsRouteImport } from './routes/interviews'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as JoinSessionRouteImport } from './routes/join-session'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ScreeningRouteImport } from './routes/screening'
import { Route as SelectRoleRouteImport } from './routes/select-role'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SimulationRouteImport } from './routes/simulation'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as TalentPoolRouteImport } from './routes/talent-pool'
import { Route as ApplyJobIdRouteImport } from './routes/apply.$jobId'
import { Route as CandidatesIdRouteImport } from './routes/candidates_.$id'
import { Route as ClassesIdRouteImport } from './routes/classes_.$id'
import { Route as InterviewRoomIdRouteImport } from './routes/interview-room.$id'
import { Route as JobsIdRouteImport } from './routes/jobs_.$id'
import { Route as JoinCodeRouteImport } from './routes/join.$code'
import { Route as PresentSessionIdRouteImport } from './routes/present.$sessionId'
import { Route as SessionsIdRouteImport } from './routes/sessions_.$id'
import { Route as AdminLecturersIdRouteImport } from './routes/admin_.lecturers.$id'
import { Route as ApiPublicAiGenerateRouteImport } from './routes/api/public/ai-generate'
import { Route as ApiPublicApplyRouteImport } from './routes/api/public/apply'
import { Route as ApiPublicJobRouteImport } from './routes/api/public/job'
import { Route as ApiPublicApplyPageJobIdRouteImport } from './routes/api/public/apply-page.$jobId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AiJobsRoute = AiJobsRouteImport.update({
  id: '/ai-jobs',
  path: '/ai-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesRoute = CandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const EthicsRoute = EthicsRouteImport.update({
  id: '/ethics',
  path: '/ethics',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewsRoute = InterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinSessionRoute = JoinSessionRouteImport.update({
  id: '/join-session',
  path: '/join-session',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreeningRoute = ScreeningRouteImport.update({
  id: '/screening',
  path: '/screening',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectRoleRoute = SelectRoleRouteImport.update({
  id: '/select-role',
  path: '/select-role',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationRoute = SimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentPoolRoute = TalentPoolRouteImport.update({
  id: '/talent-pool',
  path: '/talent-pool',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyJobIdRoute = ApplyJobIdRouteImport.update({
  id: '/apply/$jobId',
  path: '/apply/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesIdRoute = CandidatesIdRouteImport.update({
  id: '/candidates_/$id',
  path: '/candidates/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesIdRoute = ClassesIdRouteImport.update({
  id: '/classes_/$id',
  path: '/classes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewRoomIdRoute = InterviewRoomIdRouteImport.update({
  id: '/interview-room/$id',
  path: '/interview-room/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: '/jobs_/$id',
  path: '/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentSessionIdRoute = PresentSessionIdRouteImport.update({
  id: '/present/$sessionId',
  path: '/present/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIdRoute = SessionsIdRouteImport.update({
  id: '/sessions_/$id',
  path: '/sessions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLecturersIdRoute = AdminLecturersIdRouteImport.update({
  id: '/admin_/lecturers/$id',
  path: '/admin/lecturers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAiGenerateRoute = ApiPublicAiGenerateRouteImport.update({
  id: '/api/public/ai-generate',
  path: '/api/public/ai-generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicApplyRoute = ApiPublicApplyRouteImport.update({
  id: '/api/public/apply',
  path: '/api/public/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicJobRoute = ApiPublicJobRouteImport.update({
  id: '/api/public/job',
  path: '/api/public/job',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicApplyPageJobIdRoute = ApiPublicApplyPageJobIdRouteImport.update({
  id: '/api/public/apply-page/$jobId',
  path: '/api/public/apply-page/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-jobs': typeof AiJobsRoute
  '/billing': typeof BillingRoute
  '/candidates': typeof CandidatesRoute
  '/classes': typeof ClassesRoute
  '/ethics': typeof EthicsRoute
  '/interviews': typeof InterviewsRoute
  '/jobs': typeof JobsRoute
  '/join-session': typeof JoinSessionRoute
  '/login': typeof LoginRoute
  '/offers': typeof OffersRoute
  '/onboarding': typeof OnboardingRoute
  '/pending': typeof PendingRoute
  '/pipeline': typeof PipelineRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/screening': typeof ScreeningRoute
  '/select-role': typeof SelectRoleRoute
  '/sessions': typeof SessionsRoute
  '/signup': typeof SignupRoute
  '/simulation': typeof SimulationRoute
  '/students': typeof StudentsRoute
  '/talent-pool': typeof TalentPoolRoute
  '/apply/$jobId': typeof ApplyJobIdRoute
  '/candidates/$id': typeof CandidatesIdRoute
  '/classes/$id': typeof ClassesIdRoute
  '/interview-room/$id': typeof InterviewRoomIdRoute
  '/jobs/$id': typeof JobsIdRoute
  '/join/$code': typeof JoinCodeRoute
  '/present/$sessionId': typeof PresentSessionIdRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/admin/lecturers/$id': typeof AdminLecturersIdRoute
  '/api/public/ai-generate': typeof ApiPublicAiGenerateRoute
  '/api/public/apply': typeof ApiPublicApplyRoute
  '/api/public/job': typeof ApiPublicJobRoute
  '/api/public/apply-page/$jobId': typeof ApiPublicApplyPageJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-jobs': typeof AiJobsRoute
  '/billing': typeof BillingRoute
  '/candidates': typeof CandidatesRoute
  '/classes': typeof ClassesRoute
  '/ethics': typeof EthicsRoute
  '/interviews': typeof InterviewsRoute
  '/jobs': typeof JobsRoute
  '/join-session': typeof JoinSessionRoute
  '/login': typeof LoginRoute
  '/offers': typeof OffersRoute
  '/onboarding': typeof OnboardingRoute
  '/pending': typeof PendingRoute
  '/pipeline': typeof PipelineRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/screening': typeof ScreeningRoute
  '/select-role': typeof SelectRoleRoute
  '/sessions': typeof SessionsRoute
  '/signup': typeof SignupRoute
  '/simulation': typeof SimulationRoute
  '/students': typeof StudentsRoute
  '/talent-pool': typeof TalentPoolRoute
  '/apply/$jobId': typeof ApplyJobIdRoute
  '/candidates/$id': typeof CandidatesIdRoute
  '/classes/$id': typeof ClassesIdRoute
  '/interview-room/$id': typeof InterviewRoomIdRoute
  '/jobs/$id': typeof JobsIdRoute
  '/join/$code': typeof JoinCodeRoute
  '/present/$sessionId': typeof PresentSessionIdRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/admin/lecturers/$id': typeof AdminLecturersIdRoute
  '/api/public/ai-generate': typeof ApiPublicAiGenerateRoute
  '/api/public/apply': typeof ApiPublicApplyRoute
  '/api/public/job': typeof ApiPublicJobRoute
  '/api/public/apply-page/$jobId': typeof ApiPublicApplyPageJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-jobs': typeof AiJobsRoute
  '/billing': typeof BillingRoute
  '/candidates': typeof CandidatesRoute
  '/classes': typeof ClassesRoute
  '/ethics': typeof EthicsRoute
  '/interviews': typeof InterviewsRoute
  '/jobs': typeof JobsRoute
  '/join-session': typeof JoinSessionRoute
  '/login': typeof LoginRoute
  '/offers': typeof OffersRoute
  '/onboarding': typeof OnboardingRoute
  '/pending': typeof PendingRoute
  '/pipeline': typeof PipelineRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/screening': typeof ScreeningRoute
  '/select-role': typeof SelectRoleRoute
  '/sessions': typeof SessionsRoute
  '/signup': typeof SignupRoute
  '/simulation': typeof SimulationRoute
  '/students': typeof StudentsRoute
  '/talent-pool': typeof TalentPoolRoute
  '/apply/$jobId': typeof ApplyJobIdRoute
  '/candidates_/$id': typeof CandidatesIdRoute
  '/classes_/$id': typeof ClassesIdRoute
  '/interview-room/$id': typeof InterviewRoomIdRoute
  '/jobs_/$id': typeof JobsIdRoute
  '/join/$code': typeof JoinCodeRoute
  '/present/$sessionId': typeof PresentSessionIdRoute
  '/sessions_/$id': typeof SessionsIdRoute
  '/admin_/lecturers/$id': typeof AdminLecturersIdRoute
  '/api/public/ai-generate': typeof ApiPublicAiGenerateRoute
  '/api/public/apply': typeof ApiPublicApplyRoute
  '/api/public/job': typeof ApiPublicJobRoute
  '/api/public/apply-page/$jobId': typeof ApiPublicApplyPageJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ai-jobs'
    | '/billing'
    | '/candidates'
    | '/classes'
    | '/ethics'
    | '/interviews'
    | '/jobs'
    | '/join-session'
    | '/login'
    | '/offers'
    | '/onboarding'
    | '/pending'
    | '/pipeline'
    | '/reports'
    | '/reset-password'
    | '/screening'
    | '/select-role'
    | '/sessions'
    | '/signup'
    | '/simulation'
    | '/students'
    | '/talent-pool'
    | '/apply/$jobId'
    | '/candidates/$id'
    | '/classes/$id'
    | '/interview-room/$id'
    | '/jobs/$id'
    | '/join/$code'
    | '/present/$sessionId'
    | '/sessions/$id'
    | '/admin/lecturers/$id'
    | '/api/public/ai-generate'
    | '/api/public/apply'
    | '/api/public/job'
    | '/api/public/apply-page/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ai-jobs'
    | '/billing'
    | '/candidates'
    | '/classes'
    | '/ethics'
    | '/interviews'
    | '/jobs'
    | '/join-session'
    | '/login'
    | '/offers'
    | '/onboarding'
    | '/pending'
    | '/pipeline'
    | '/reports'
    | '/reset-password'
    | '/screening'
    | '/select-role'
    | '/sessions'
    | '/signup'
    | '/simulation'
    | '/students'
    | '/talent-pool'
    | '/apply/$jobId'
    | '/candidates/$id'
    | '/classes/$id'
    | '/interview-room/$id'
    | '/jobs/$id'
    | '/join/$code'
    | '/present/$sessionId'
    | '/sessions/$id'
    | '/admin/lecturers/$id'
    | '/api/public/ai-generate'
    | '/api/public/apply'
    | '/api/public/job'
    | '/api/public/apply-page/$jobId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ai-jobs'
    | '/billing'
    | '/candidates'
    | '/classes'
    | '/ethics'
    | '/interviews'
    | '/jobs'
    | '/join-session'
    | '/login'
    | '/offers'
    | '/onboarding'
    | '/pending'
    | '/pipeline'
    | '/reports'
    | '/reset-password'
    | '/screening'
    | '/select-role'
    | '/sessions'
    | '/signup'
    | '/simulation'
    | '/students'
    | '/talent-pool'
    | '/apply/$jobId'
    | '/candidates_/$id'
    | '/classes_/$id'
    | '/interview-room/$id'
    | '/jobs_/$id'
    | '/join/$code'
    | '/present/$sessionId'
    | '/sessions_/$id'
    | '/admin_/lecturers/$id'
    | '/api/public/ai-generate'
    | '/api/public/apply'
    | '/api/public/job'
    | '/api/public/apply-page/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AiJobsRoute: typeof AiJobsRoute
  BillingRoute: typeof BillingRoute
  CandidatesRoute: typeof CandidatesRoute
  ClassesRoute: typeof ClassesRoute
  EthicsRoute: typeof EthicsRoute
  InterviewsRoute: typeof InterviewsRoute
  JobsRoute: typeof JobsRoute
  JoinSessionRoute: typeof JoinSessionRoute
  LoginRoute: typeof LoginRoute
  OffersRoute: typeof OffersRoute
  OnboardingRoute: typeof OnboardingRoute
  PendingRoute: typeof PendingRoute
  PipelineRoute: typeof PipelineRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ScreeningRoute: typeof ScreeningRoute
  SelectRoleRoute: typeof SelectRoleRoute
  SessionsRoute: typeof SessionsRoute
  SignupRoute: typeof SignupRoute
  SimulationRoute: typeof SimulationRoute
  StudentsRoute: typeof StudentsRoute
  TalentPoolRoute: typeof TalentPoolRoute
  ApplyJobIdRoute: typeof ApplyJobIdRoute
  CandidatesIdRoute: typeof CandidatesIdRoute
  ClassesIdRoute: typeof ClassesIdRoute
  InterviewRoomIdRoute: typeof InterviewRoomIdRoute
  JobsIdRoute: typeof JobsIdRoute
  JoinCodeRoute: typeof JoinCodeRoute
  PresentSessionIdRoute: typeof PresentSessionIdRoute
  SessionsIdRoute: typeof SessionsIdRoute
  AdminLecturersIdRoute: typeof AdminLecturersIdRoute
  ApiPublicAiGenerateRoute: typeof ApiPublicAiGenerateRoute
  ApiPublicApplyRoute: typeof ApiPublicApplyRoute
  ApiPublicJobRoute: typeof ApiPublicJobRoute
  ApiPublicApplyPageJobIdRoute: typeof ApiPublicApplyPageJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-jobs': {
      id: '/ai-jobs'
      path: '/ai-jobs'
      fullPath: '/ai-jobs'
      preLoaderRoute: typeof AiJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates': {
      id: '/candidates'
      path: '/candidates'
      fullPath: '/candidates'
      preLoaderRoute: typeof CandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ethics': {
      id: '/ethics'
      path: '/ethics'
      fullPath: '/ethics'
      preLoaderRoute: typeof EthicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interviews': {
      id: '/interviews'
      path: '/interviews'
      fullPath: '/interviews'
      preLoaderRoute: typeof InterviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-session': {
      id: '/join-session'
      path: '/join-session'
      fullPath: '/join-session'
      preLoaderRoute: typeof JoinSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screening': {
      id: '/screening'
      path: '/screening'
      fullPath: '/screening'
      preLoaderRoute: typeof ScreeningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-role': {
      id: '/select-role'
      path: '/select-role'
      fullPath: '/select-role'
      preLoaderRoute: typeof SelectRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulation': {
      id: '/simulation'
      path: '/simulation'
      fullPath: '/simulation'
      preLoaderRoute: typeof SimulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent-pool': {
      id: '/talent-pool'
      path: '/talent-pool'
      fullPath: '/talent-pool'
      preLoaderRoute: typeof TalentPoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/$jobId': {
      id: '/apply/$jobId'
      path: '/apply/$jobId'
      fullPath: '/apply/$jobId'
      preLoaderRoute: typeof ApplyJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates_/$id': {
      id: '/candidates_/$id'
      path: '/candidates/$id'
      fullPath: '/candidates/$id'
      preLoaderRoute: typeof CandidatesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes_/$id': {
      id: '/classes_/$id'
      path: '/classes/$id'
      fullPath: '/classes/$id'
      preLoaderRoute: typeof ClassesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview-room/$id': {
      id: '/interview-room/$id'
      path: '/interview-room/$id'
      fullPath: '/interview-room/$id'
      preLoaderRoute: typeof InterviewRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs_/$id': {
      id: '/jobs_/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$code': {
      id: '/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/present/$sessionId': {
      id: '/present/$sessionId'
      path: '/present/$sessionId'
      fullPath: '/present/$sessionId'
      preLoaderRoute: typeof PresentSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions_/$id': {
      id: '/sessions_/$id'
      path: '/sessions/$id'
      fullPath: '/sessions/$id'
      preLoaderRoute: typeof SessionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/lecturers/$id': {
      id: '/admin_/lecturers/$id'
      path: '/admin/lecturers/$id'
      fullPath: '/admin/lecturers/$id'
      preLoaderRoute: typeof AdminLecturersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai-generate': {
      id: '/api/public/ai-generate'
      path: '/api/public/ai-generate'
      fullPath: '/api/public/ai-generate'
      preLoaderRoute: typeof ApiPublicAiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/apply': {
      id: '/api/public/apply'
      path: '/api/public/apply'
      fullPath: '/api/public/apply'
      preLoaderRoute: typeof ApiPublicApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/job': {
      id: '/api/public/job'
      path: '/api/public/job'
      fullPath: '/api/public/job'
      preLoaderRoute: typeof ApiPublicJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/apply-page/$jobId': {
      id: '/api/public/apply-page/$jobId'
      path: '/api/public/apply-page/$jobId'
      fullPath: '/api/public/apply-page/$jobId'
      preLoaderRoute: typeof ApiPublicApplyPageJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AiJobsRoute: AiJobsRoute,
  BillingRoute: BillingRoute,
  CandidatesRoute: CandidatesRoute,
  ClassesRoute: ClassesRoute,
  EthicsRoute: EthicsRoute,
  InterviewsRoute: InterviewsRoute,
  JobsRoute: JobsRoute,
  JoinSessionRoute: JoinSessionRoute,
  LoginRoute: LoginRoute,
  OffersRoute: OffersRoute,
  OnboardingRoute: OnboardingRoute,
  PendingRoute: PendingRoute,
  PipelineRoute: PipelineRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ScreeningRoute: ScreeningRoute,
  SelectRoleRoute: SelectRoleRoute,
  SessionsRoute: SessionsRoute,
  SignupRoute: SignupRoute,
  SimulationRoute: SimulationRoute,
  StudentsRoute: StudentsRoute,
  TalentPoolRoute: TalentPoolRoute,
  ApplyJobIdRoute: ApplyJobIdRoute,
  CandidatesIdRoute: CandidatesIdRoute,
  ClassesIdRoute: ClassesIdRoute,
  InterviewRoomIdRoute: InterviewRoomIdRoute,
  JobsIdRoute: JobsIdRoute,
  JoinCodeRoute: JoinCodeRoute,
  PresentSessionIdRoute: PresentSessionIdRoute,
  SessionsIdRoute: SessionsIdRoute,
  AdminLecturersIdRoute: AdminLecturersIdRoute,
  ApiPublicAiGenerateRoute: ApiPublicAiGenerateRoute,
  ApiPublicApplyRoute: ApiPublicApplyRoute,
  ApiPublicJobRoute: ApiPublicJobRoute,
  ApiPublicApplyPageJobIdRoute: ApiPublicApplyPageJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
